{{- $fullName := include "fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    # ingress.kubernetes.io/rewrite-target: /
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host:
    http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: 9080
      {{- end }}
      {{- range .Values.ingress.denyPaths }}
      - path: {{ . }}
        backend:
          serviceName: default-backend
          servicePort: 80
      {{- end }}
