{{- $fullName := include "fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $contextRoot := .Values.contextRoot -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      {{- range $ingressPaths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: 9080
      {{- end }}
      - path: {{ $contextRoot }}
        backend:
          serviceName: default-backend
          servicePort: 80
  {{- end }}
