{{ if .Values.ingress.enabled }}
{{- $fullName := include "fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    # ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route-{{ $fullName }}"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/server-snippet: |-
    {{- range .Values.ingress.denyPaths }}
      location {{ . }} {
          deny all;
      }
    {{- end }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host:
    http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
      {{- end }}
{{ end }}