apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host:
    http:
      paths:
      - path: {{ .Values.contextRoot }}
        backend:
          serviceName: {{ include "fullname" . }}
          servicePort: 9080
