apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "subsystem" . }}
  # annotations:
  #   ingress.kubernetes.io/rewrite-target: /
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host:
    http:
      paths:
      - path: {{ .Values.contextRoot }}
        backend:
          serviceName: {{ include "subsystem" . }}
          servicePort: 9080
