{{ if .Values.ingress.enabled }}
{{- $fullName := include "fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ .Values.ingress.annotationsPrefix }}/ssl-redirect: "false"
    {{ .Values.ingress.annotationsPrefix }}/affinity: "cookie"
    {{ .Values.ingress.annotationsPrefix }}/session-cookie-name: "route-{{ $fullName }}"
    {{ .Values.ingress.annotationsPrefix }}/session-cookie-hash: "sha1"
    {{ .Values.ingress.annotationsPrefix }}/server-snippet: |-
    {{- range .Values.ingress.denyPaths }}
      location {{ . }} {
          deny all;
      }
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
      {{- end }}
{{ end }}