apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-np
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ include "fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9080
    protocol: TCP
