apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "fullname" . }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 6 }}
      initContainers:
      - name: app
        image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
        imagePullPolicy: {{ .Values.appImage.pullPolicy }}
        command:
        - sh
        - -c
        - |
          cp -rp /config/* /mnt/config/
          cp -rp /userhome/ida/* /mnt/userhome/ida/
          chown -R 1001:0 /mnt/config
          chown -R 1001:0 /mnt/userhome/ida
          sysctl -w net.core.somaxconn=5000
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
        - name: ida-volume
          mountPath: /mnt/userhome/ida
      containers:
      - name: liberty
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9080
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        env:
        - name: LICENSE
          value: "accept"
        - name : WLP_SKIP_UMASK
          value: "true"
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: {{ .Values.logs.consoleFormat }}
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: {{ .Values.logs.consoleLogLevel }}
        - name: WLP_LOGGING_CONSOLE_SOURCE
          value: {{ .Values.logs.consoleSource }}
        - name: MP_METRICS_TAGS
          value: "app={{ .Release.Name }}"
        - name: JVM_ARGS
          value: {{ .Values.env.jvmArgs }}
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        {{- range .Values.configMapNames }}
        - configMapRef:
            name: {{ . | quote }}
        {{- end }}
        {{- range .Values.secretNames }}
        - secretRef:
            name: {{ . | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: ida-volume
          mountPath: /userhome/ida
        - name: liberty-pvc
          mountPath: /logs
          subPath: logs
        - name: liberty-pvc
          mountPath: /Local/core/wlp
          subPath: dump
        - name: liberty-pvc
          mountPath: /Local/uservar000/ida/log
          subPath: applogs
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: ida-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name | quote }}
    spec:
      storageClassName: {{ .Release.Name }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
