kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-9.188.124.27
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/mysql-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "9.188.124.27"
