# Init Containerのイメージの指定
appImage:
  repository: mycluster.icp:8500/prod/myliberty-app
  tag: "0.0.1"
  pullPolicy: Always    # Always(default), Never, IfNotPresent

# Liberty Containerのイメージの指定
image:
  repository: mycluster.icp:8500/prod/myliberty
  tag: "18.0.0.4"
  pullPolicy: Always

replicaCount: 1

updateStrategy:
  type: OnDelete
  # type: RollingUpdate
  # rollingUpdate:
  #   partition: 0

terminationGracePeriodSeconds: 30    # Defaults to 30 seconds.

livenessProbe:
  httpGet:
    path: /sample/index.html
    port: 9080
  initialDelaySeconds: 180   # default no delay
  periodSeconds: 10          # Default to 10 seconds. Minimum value is 1.
  timeoutSeconds: 1          # Defaults to 1 second. Minimum value is 1. 
  failureThreshold: 3        # Defaults to 3. Minimum value is 1.
  successThreshold: 1        # Defaults to 1. Must be 1 for liveness. Minimum value is 1.

readinessProbe:
  httpGet:
    path: /sample/index.html
    port: 9080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 512Mi

hostAliases:
- ip: "127.0.0.1"
  hostnames:
  - "foo.local"
  - "bar.local"
- ip: "10.1.2.3"
  hostnames:
  - "foo.remote"
  - "bar.remote"

service:
  port: 9080

ingress:
  enabled: true
  paths:
  - /sample
  denyPaths:
  - /sample/admin

persistence:
  name: "liberty-pvc"
  size: "1Gi"

logs:
  consoleFormat: basic      # basic(default) or json
  consoleLogLevel: info     # info, audit(default), warning, error, and off
  consoleSource: message    # message(default), trace, accessLog, ffdc, and audit

env:
  jvmArgs: ""

secretNames:
- common-env
configMapNames:
- common-env
