app:
  repository: mycluster.icp:8500/sugi/myliberty-app
  tag: "0.0.1"
  pullPolicy: Always

liberty:
  repository: mycluster.icp:8500/sugi/myliberty
  tag: "18.0.0.3"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 256Mi

persistence:
  size: "1Gi"

secretName: common-env
configMapName: common-env
contextRoot: "/"

