# Init Containerのイメージの指定
app:
  repository: mycluster.icp:8500/sugi/myliberty-app
  tag: "0.0.1"
  pullPolicy: Always

# Liberty Containerのイメージの指定
liberty:
  repository: mycluster.icp:8500/sugi/myliberty
  tag: "18.0.0.3"
  pullPolicy: IfNotPresent

replicaCount: 1

contextRoot: /top

livenessProbe:
  httpGet:
    path: /top/index.html
    port: 9080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /top/index.html
    port: 9080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 512Mi

service:
  port: 9080

persistence:
  name: "liberty-pvc"
  size: "1Gi"

logs:
  consoleFormat: standard
  consoleLogLevel: info
  consoleSource: message

env:
  jvmArgs: ""

secretName: common-env
configMapName: common-env



