apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mysql-init
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      containers:
      - name: init-hellomysql
        image: "{{ .Values.init.repository }}:{{ .Values.init.tag }}"
        imagePullPolicy: {{ .Values.init.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: root-password
        command: ["sh", "-c"]
        args: ["mysql -u root -p${MYSQL_ROOT_PASSWORD} -h {{ .Release.Name }}-mysql < init.sql"]
      restartPolicy: OnFailure
